INSERT INTO unidades (id, area_id, nombre) VALUES
('DRP-UC','1R','Unidad de Control'),
('DRP-URC','1R','Unidad de Registro y Certificación'),
('DDBRAE-UDB','2D','Unidad de Disposición de Bienes'),
('DDBRAE-UL','2D','Unidad de Liquidación'),
('DLEGSS-UC','3L','Unidad de Contabilidad'),
('DLEGSS-URC','3L','Unidad de Recuperación de Cartera'),
('DLEGSS-UARL','3L','Unidad Análisis y Recuperación Legal'),
('DAF-PLA','4A','Planificación'),
('DAF-SIS','4A','Sistemas'),
('DAF-RRHH','4A','Recursos Humanos'),
('DAF-UF','4A','Unidad Financiera'),
('DAF-UA','4A','Unidad Administrativa'),
('DJ-UAJ','5J','Unidad de Análisis Jurídico'),
('DJ-UGJ','5J','Unidad de Gestión Jurídica'),
('DOR-DOR','6O','Oficina Distrital SENAPE Oruro'),
('DCB-DCB','6O','Oficina Distrital SENAPE Cochabamba'),
('DSC-DSC','6O','Oficina Distrital SENAPE Santa Cruz'),
('DCH-DCH','6O','Oficina Distrital SENAPE Chuquisaca'),
('DBE-DBE','6O','Oficina Distrital SENAPE Beni'),
('AI-AI','7I','Unidad de Auditoría Interna'),
('AT-AT','8T','Área de Transparencia');